apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
spec:
  selector:
    app: hello-python-blue
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
